services:
  godot:
    build: .
    container_name: godot-mcp
    restart: unless-stopped
    ports:
      - "9060:9060" # MCP server port
    environment:
      # Dewey connection
      - DEWEY_MCP_URL=ws://dewey-mcp:9020
      - DEWEY_CONNECT_TIMEOUT=30

      # Worker configuration
      - BATCH_SIZE=100
      - BATCH_TIMEOUT_MS=100
      - RETRY_MAX_ATTEMPTS=5
      - RETRY_INITIAL_DELAY=1
      - RETRY_MAX_DELAY=30

      # Redis configuration (internal)
      - REDIS_HOST=localhost
      - REDIS_PORT=6379
      - LOG_QUEUE_NAME=logs:queue
      - MAX_QUEUE_SIZE=100000  # REQ-GOD-004, REQ-PERF-003

    volumes:
      - godot_redis_data:/data
    networks:
      - iccm_network

volumes:
  godot_redis_data:

networks:
  iccm_network:
    external: true
