version: '3.8'

services:
  playfair-mcp:
    container_name: playfair-mcp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      # Map host port 9040 to container port 8040 for MCP and health checks
      - "9040:8040"
    networks:
      # Connect to the external ICCM network
      - iccm_network
    environment:
      # Application Configuration
      - NODE_ENV=production
      - PORT=8040
      - LOG_LEVEL=info
      # Godot Logging Configuration
      - GODOT_URL=ws://godot-mcp:9060
      - LOGGING_ENABLED=true
      # Worker Pool Configuration
      - WORKER_POOL_SIZE=3
      - MAX_QUEUE_SIZE=50
      # Resource Limits
      - RENDER_TIMEOUT_MS=60000
      - MAX_CONTENT_LINES=10000
      - MAX_PNG_WIDTH=8192
      - MAX_PNG_HEIGHT=8192
      # File Output Configuration
      - DEFAULT_OUTPUT_DIR=/mnt/irina_storage/files/temp/playfair
    deploy:
      # Enforce resource limits at the container level
      resources:
        limits:
          memory: 2G
          cpus: '2.0'
    restart: unless-stopped
    volumes:
      # Persist temporary files if needed for debugging, though the app should clean up
      - playfair-temp:/tmp/playfair
      # Mount ICCM project directory for direct file access
      - /mnt/projects/ICCM:/mnt/projects/ICCM
      # Mount Horace storage for diagram output
      - irina_storage_files:/mnt/irina_storage/files

networks:
  iccm_network:
    # This configuration assumes the 'iccm_network' is created by another compose file or manually.
    external: true

volumes:
  playfair-temp:
    # Define the named volume for temporary data

  irina_storage_files:
    # External volume managed by Horace
    driver: local
    driver_opts:
      type: none
      device: /mnt/projects/ICCM/irina_storage_test/files
      o: bind