version: '3.8'

services:
  claude-code:
    build: .
    image: iccm/claude-code:latest
    container_name: claude-code-container
    stdin_open: true
    tty: true
    networks:
      - iccm-network
    volumes:
      # Mount workspace
      - /mnt/projects:/mnt/projects
      - ${PWD}:/workspace

      # Mount MCP config (will create if needed)
      - ./config:/root/.config/claude-code

      # Mount SSH keys for git operations (if needed)
      - ${HOME}/.ssh:/root/.ssh:ro

      # Mount git config (if needed)
      - ${HOME}/.gitconfig:/root/.gitconfig:ro

    environment:
      # API Configuration - route through KGB HTTP gateway
      - ANTHROPIC_BASE_URL=http://host.docker.internal:8089/v1

      # API Key - from host environment
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}

      # MCP Relay connection (already running on host)
      # Will connect to KGB on host network

    extra_hosts:
      # Access host services (KGB on localhost:8089 and localhost:9000)
      - "host.docker.internal:host-gateway"

networks:
  iccm-network:
    name: iccm-network
    driver: bridge
