version: '3.8'

services:
  claude-code:
    build: .
    image: iccm/claude-code:latest
    container_name: claude-code-container
    stdin_open: true
    tty: true
    command: /bin/bash
    networks:
      - iccm-network
    volumes:
      # Mount workspace
      - /mnt/projects:/mnt/projects
      - ${PWD}:/workspace

      # Mount MCP config (will create if needed)
      - ./config:/root/.config/claude-code

      # Mount MCP relay backends config (containerized mode with KGB routing)
      - ./config/backends.yaml:/mnt/projects/ICCM/mcp-relay/backends.yaml

      # Mount SSH keys for git operations (if needed)
      - ${HOME}/.ssh:/root/.ssh:ro

      # Mount git config (if needed)
      - ${HOME}/.gitconfig:/root/.gitconfig:ro

    environment:
      # API Configuration - route through KGB HTTP gateway
      # Note: No /v1 suffix - Claude Code will add it
      - ANTHROPIC_BASE_URL=http://kgb-proxy:8089

      # API Key - from host environment
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}

      # MCP Relay connection - connects to KGB WebSocket spy
      # Both Claude and KGB are on same Docker network (iccm_network)

networks:
  iccm-network:
    name: iccm_network
    external: true
